[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "jupyter-draft-and-publish"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.7,<5"
python = "3.13.*"
polars = ">=1.33.1,<2"
matplotlib = ">=3.10.6,<4"
jupytext = ">=1.17.3,<2"
mystmd = ">=1.6.1,<2"
jupyterlab-myst = ">=2.4.2,<3"
